---
spring.main.allow-bean-definition-overriding: true

spring:
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  web:
    resources:
      add-mappings: false
  cache:
    ehcache:
      config: classpath:ehcache.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect

  profiles:
    group:
      local: "local-envs,local-db"
      dev: ""
      production: ""
    active: local

---
# local env
spring.config.activate.on-profile: local-envs

---
# local db
spring.config.activate.on-profile: local-db

spring:
  datasource:
    one:
      xa-properties:
        url: jdbc:mysql://127.0.0.1:3306/jta_1?serverTimezone=UTC&characterEncoding=UTF-8
        user: root
        password: nextage2020!
      xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
      unique-resource-name: 'one'
      test-query: SELECT 1
      min-pool-size: 5
      max-pool-size: 10
    two:
      xa-properties:
        url: jdbc:mysql://127.0.0.1:3306/jta_2?serverTimezone=UTC&characterEncoding=UTF-8
        user: root
        password: nextage2020!
      xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
      unique-resource-name: 'two'
      min-pool-size: 2
      max-pool-size: 2

#spring:
#  datasource:
#    admin:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: "jdbc:mysql://127.0.0.1:3306/my_advanced_admin?serverTimezone=UTC&characterEncoding=UTF-8"
#      username: "root"
#      password: "nextage2020!"
#    member:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: "jdbc:mysql://127.0.0.1:3306/my_advanced_member?serverTimezone=UTC&characterEncoding=UTF-8"
#      username: "root"
#      password: "nextage2020!"

